// GETTING-ON-AIR.md — the playout-side quick guide bundled into exported packages.
// A condensed, package-local edition of docs/PLAYOUT_INTEGRATION.md, written for the person
// configuring the playout machine (who never sees this repo). Keep the two in agreement:
// anything corrected here is usually wrong in the doc too.

export function onAirGuideMd(): string {
  return `# Getting this package on air

Generated by NoaCG Studio. Everything in this folder is self-contained — relative paths,
bundled fonts and GSAP, no internet needed to render.

## The three rules every browser playout shares

- **Transparency is built in.** Do not add a chroma key. A black/white box behind the graphic
  means the host is forcing an opaque background — clear its custom CSS/background setting.
- **Match the resolution exactly** (the README states this package's canvas). Set the browser
  source to the same numbers; resize the source, never the resulting layer.
- **Match the channel's frame rate** on the browser source.

## SPX Graphics

1. Extract this folder into SPX's \`ASSETS/templates/\` directory.
2. Add the template to a rundown — the operator fields come from the template's own definition.
3. **Play** airs it, **Continue** walks its steps, **Stop** plays it out.

## CasparCG

Use the HTML producer. For a folder package, point at the template's own .html file; a
single-file CasparCG export drops straight into the server's template folder:

    CG 1-20 ADD 1 "<template-name>" 1 "<templateData>...</templateData>"
    CG 1-20 PLAY

On CasparCG **2.3.x** the bundled browser is old (Chromium 6x): if you hand-edit template code,
avoid modern syntax like \`?.\` — a too-modern page dies silently with a SyntaxError only in the
server log. Generated code already respects that bar.

## OBS Studio / vMix

Add a **Browser** source (OBS) or **Web Browser** input (vMix), point it at the graphic's .html
file, set width/height to the graphic's resolution, leave the background alone.

## The bundled control panel — read this before using it

\`controlpanel.html\` drives the graphic over a **same-origin browser channel**. That means:

- **Works:** both pages opened from the same web address (http:// or https://, same host and
  port) in the same browser — for example SPX's own template server, or any local web server.
- **Does not work:** opening the files straight from disk (\`file://\`) — the browser gives every
  local file its own private origin, so the pages cannot see each other. The panel will tell you
  when nothing is answering.
- **Does not work:** driving a graphic that is loaded inside OBS/vMix/CasparCG from a panel in
  your normal browser — those hosts run their own separate browser engine. Use the host's own
  controls (SPX rundown, CasparCG commands), or an OBS **Custom Browser Dock** pointing at the
  panel beside a same-origin graphic, or the production's hosted control page (cloud).

In an SPX or CasparCG rundown you normally do not need the panel at all — the host is the
controller there.

## When it does not work

| Symptom | Usually means | Fix |
|---|---|---|
| Layer on air, nothing renders, no error | CasparCG 2.3.x rejected edited JS | Check server log for SyntaxError; remove \`?.\`/\`??\` |
| Black/white box behind the graphic | Host forcing opaque background | Clear custom CSS/background; no chroma key |
| Soft or wrong-sized graphic | Source dimensions do not match the design | Set the source to the graphic's own resolution |
| Control panel buttons do nothing | Pages not same-origin (file://, or different hosts) | Serve both over one http address, or use the host's own controls |
`;
}
