// GENERATED by scripts/build-google-fonts-index.mjs - do not edit by hand.
// 1942 families from https://fonts.google.com/metadata/fonts, in popularity order.
//
// One line per family: name | category (s/f/d/h/m) | the upright weights it publishes.
// Names only - no font bytes. src/model/googleFonts.ts parses it lazily.

export const GOOGLE_FONTS_GENERATED = '2026-08-16';

export const GOOGLE_FONTS_RAW = `Roboto|s|100 200 300 400 500 600 700 800 900
Open Sans|s|300 400 500 600 700 800
Google Sans|s|400 500 600 700
Inter|s|100 200 300 400 500 600 700 800 900
Montserrat|s|100 200 300 400 500 600 700 800 900
Poppins|s|100 200 300 400 500 600 700 800 900
Noto Sans JP|s|100 200 300 400 500 600 700 800 900
Lato|s|100 300 400 700 900
Arimo|s|400 500 600 700
Roboto Condensed|s|100 200 300 400 500 600 700 800 900
Roboto Mono|m|100 200 300 400 500 600 700
Oswald|s|200 300 400 500 600 700
Noto Sans|s|100 200 300 400 500 600 700 800 900
DM Sans|s|100 200 300 400 500 600 700 800 900 1000
Raleway|s|100 200 300 400 500 600 700 800 900
Nunito|s|200 300 400 500 600 700 800 900 1000
Playfair Display|f|400 500 600 700 800 900
Nunito Sans|s|200 300 400 500 600 700 800 900 1000
Roboto Slab|f|100 200 300 400 500 600 700 800 900
Rubik|s|300 400 500 600 700 800 900
Archivo Black|s|400
Outfit|s|100 200 300 400 500 600 700 800 900
Ubuntu|s|300 400 500 700
Manrope|s|200 300 400 500 600 700 800
Kanit|s|100 200 300 400 500 600 700 800 900
Noto Sans KR|s|100 200 300 400 500 600 700 800 900
Merriweather|f|300 400 500 600 700 800 900
Work Sans|s|100 200 300 400 500 600 700 800 900
Black Ops One|d|400
Prompt|s|100 200 300 400 500 600 700 800 900
Lora|f|400 500 600 700
Bebas Neue|s|400
Saira|s|100 200 300 400 500 600 700 800 900
Noto Sans TC|s|100 200 300 400 500 600 700 800 900
PT Sans|s|400 700
Figtree|s|300 400 500 600 700 800 900
Bricolage Grotesque|s|200 300 400 500 600 700 800
Plus Jakarta Sans|s|200 300 400 500 600 700 800
Mulish|s|200 300 400 500 600 700 800 900 1000
Share Tech|s|400
Smooch Sans|s|100 200 300 400 500 600 700 800 900
Barlow|s|100 200 300 400 500 600 700 800 900
Quicksand|s|300 400 500 600 700
Source Sans 3|s|200 300 400 500 600 700 800 900
Jost|s|100 200 300 400 500 600 700 800 900
Karla|s|200 300 400 500 600 700 800
IBM Plex Sans|s|100 200 300 400 500 600 700
Source Code Pro|m|200 300 400 500 600 700 800 900
Heebo|s|100 200 300 400 500 600 700 800 900
Archivo|s|100 200 300 400 500 600 700 800 900
JetBrains Mono|m|100 200 300 400 500 600 700 800
Fira Sans|s|100 200 300 400 500 600 700 800 900
Titillium Web|s|200 300 400 600 700 900
Noto Serif|f|100 200 300 400 500 600 700 800 900
Fjalla One|s|400
Space Grotesk|s|300 400 500 600 700
Noto Color Emoji|s|400
PT Serif|f|400 700
Lobster Two|d|400 700
Changa One|d|400
Noto Sans SC|s|100 200 300 400 500 600 700 800 900
Google Sans Flex|s|1 100 200 300 400 500 600 700 800 900 1000
Libre Baskerville|f|400 500 600 700
Cormorant Garamond|f|300 400 500 600 700
Dancing Script|h|400 500 600 700
Noto Serif JP|f|200 300 400 500 600 700 800 900
Libre Franklin|s|100 200 300 400 500 600 700 800 900
Barlow Condensed|s|100 200 300 400 500 600 700 800 900
Inconsolata|m|200 300 400 500 600 700 800 900
Anton|s|400
Josefin Sans|s|100 200 300 400 500 600 700
EB Garamond|f|400 500 600 700 800
Alfa Slab One|d|400
Instrument Serif|f|400
Cairo|s|200 300 400 500 600 700 800 900 1000
Public Sans|s|100 200 300 400 500 600 700 800 900
Assistant|s|200 300 400 500 600 700 800
Mukta|s|200 300 400 500 600 700 800
Roboto Flex|s|100 200 300 400 500 600 700 800 900 1000
Hind Siliguri|s|300 400 500 600 700
Lilita One|d|400
Sora|s|100 200 300 400 500 600 700 800
Fraunces|f|100 200 300 400 500 600 700 800 900
Lexend|s|100 200 300 400 500 600 700 800 900
Schibsted Grotesk|s|400 500 600 700 800 900
Inter Tight|s|100 200 300 400 500 600 700 800 900
Nanum Gothic|s|400 700 800
Cabin|s|400 500 600 700
Noto Sans Khmer|s|100 200 300 400 500 600 700 800 900
Bitter|f|100 200 300 400 500 600 700 800 900
M PLUS Rounded 1c|s|100 300 400 500 700 800 900
Dosis|s|200 300 400 500 600 700 800
Fredoka|s|300 400 500 600 700
Orbitron|s|400 500 600 700 800 900
Rajdhani|s|300 400 500 600 700
Urbanist|s|100 200 300 400 500 600 700 800 900
Red Hat Display|s|300 400 500 600 700 800 900
Exo 2|s|100 200 300 400 500 600 700 800 900
Noto Sans Telugu|s|100 200 300 400 500 600 700 800 900
IBM Plex Mono|m|100 200 300 400 500 600 700
Ramabhadra|s|400
Geist|s|100 200 300 400 500 600 700 800 900
Anek Telugu|s|100 200 300 400 500 600 700 800
Hind|s|300 400 500 600 700
Caveat|h|400 500 600 700
Instrument Sans|s|400 500 600 700
DM Serif Display|f|400
Crimson Text|f|400 600 700
Bungee|d|400
Oxygen|s|300 400 700
Pacifico|h|400
Tajawal|s|200 300 400 500 700 800 900
Cinzel|f|400 500 600 700 800 900
PT Sans Narrow|s|400 700
Gravitas One|d|400
Source Serif 4|f|200 300 400 500 600 700 800 900
Slabo 27px|f|400
Lobster|d|400
Merriweather Sans|s|300 400 500 600 700 800
Barlow Semi Condensed|s|100 200 300 400 500 600 700 800 900
Overpass|s|100 200 300 400 500 600 700 800 900
Arvo|f|400 700
Abel|s|400
Noto Sans Arabic|s|100 200 300 400 500 600 700 800 900
Teko|s|300 400 500 600 700
M PLUS 1p|s|100 300 400 500 700 800 900
Noto Serif KR|f|200 300 400 500 600 700 800 900
Comfortaa|d|300 400 500 600 700
Noto Sans Thai|s|100 200 300 400 500 600 700 800 900
Rethink Sans|s|400 500 600 700 800
Bodoni Moda|f|400 500 600 700 800 900
Maven Pro|s|400 500 600 700 800 900
Onest|s|100 200 300 400 500 600 700 800 900
Alumni Sans|s|100 200 300 400 500 600 700 800 900
Newsreader|f|200 300 400 500 600 700 800
Domine|f|400 500 600 700
Asap|s|100 200 300 400 500 600 700 800 900
Chakra Petch|s|300 400 500 600 700
ABeeZee|s|400
Shadows Into Light|h|400
Hanken Grotesk|s|100 200 300 400 500 600 700 800 900
Geist Mono|m|100 200 300 400 500 600 700 800 900
Abril Fatface|d|400
Lexend Deca|s|100 200 300 400 500 600 700 800 900
Zen Kaku Gothic New|s|300 400 500 700 900
Play|s|400 700
Zilla Slab|f|300 400 500 600 700
Questrial|s|400
Be Vietnam Pro|s|100 200 300 400 500 600 700 800 900
Space Mono|m|400 700
Almarai|s|300 400 700 800
Archivo Narrow|s|400 500 600 700
Albert Sans|s|100 200 300 400 500 600 700 800 900
Marcellus|f|400
Noto Sans Tamil|s|100 200 300 400 500 600 700 800 900
DM Mono|m|300 400 500
Exo|s|100 200 300 400 500 600 700 800 900
Varela Round|s|400
League Spartan|s|100 200 300 400 500 600 700 800 900
Cormorant|f|300 400 500 600 700
Saira Condensed|s|100 200 300 400 500 600 700 800 900
IBM Plex Serif|f|100 200 300 400 500 600 700
Unbounded|s|200 300 400 500 600 700 800 900
Great Vibes|h|400
Indie Flower|h|400
Spectral|f|200 300 400 500 600 700 800
Frank Ruhl Libre|f|300 400 500 600 700 800 900
Syne|s|400 500 600 700 800
Sofia Sans|s|1 100 200 300 400 500 600 700 800 900 1000
Righteous|d|400
Nanum Myeongjo|f|400 700 800
Noto Serif TC|f|200 300 400 500 600 700 800 900
Crimson Pro|f|200 300 400 500 600 700 800 900
Epilogue|s|100 200 300 400 500 600 700 800 900
IBM Plex Sans Arabic|s|100 200 300 400 500 600 700
Geologica|s|100 200 300 400 500 600 700 800 900
Zen Maru Gothic|s|300 400 500 700 900
Permanent Marker|h|400
Roboto Serif|f|100 200 300 400 500 600 700 800 900
Noto Serif SC|f|200 300 400 500 600 700 800 900
Satisfy|h|400
Kalam|h|300 400 700
Press Start 2P|d|400
Amiri|f|400 700
Viga|s|400
Baloo 2|d|400 500 600 700 800
Antic Slab|f|400
Angkor|d|400
Sarabun|s|100 200 300 400 500 600 700 800
News Cycle|s|400 700
Vollkorn|f|400 500 600 700 800 900
Luckiest Guy|d|400
LINE Seed JP|s|100 400 700 800
Fira Sans Condensed|s|100 200 300 400 500 600 700 800 900
Catamaran|s|100 200 300 400 500 600 700 800 900
Literata|f|200 300 400 500 600 700 800 900
DM Serif Text|f|400
Signika|s|300 400 500 600 700
Hammersmith One|s|400
Rowdies|d|300 400 700
Yellowtail|h|400
Noto Kufi Arabic|s|100 200 300 400 500 600 700 800 900
Red Hat Text|s|300 400 500 600 700
Khand|s|300 400 500 600 700
Russo One|s|400
Alegreya Sans|s|100 300 400 500 700 800 900
Prata|f|400
Shippori Mincho|f|400 500 600 700 800
IBM Plex Sans Condensed|s|100 200 300 400 500 600 700
Hind Madurai|s|300 400 500 600 700
Cardo|f|400 700
Acme|s|400
Aleo|f|100 200 300 400 500 600 700 800 900
Tinos|f|400 700
Bree Serif|f|400
Montserrat Alternates|s|100 200 300 400 500 600 700 800 900
Chivo|s|100 200 300 400 500 600 700 800 900
Special Elite|d|400
Libre Barcode 39|d|400
Baskervville|f|400 500 600 700
Tenor Sans|s|400
Encode Sans|s|100 200 300 400 500 600 700 800 900
Atkinson Hyperlegible|s|400 700
Courier Prime|m|400 700
Yanone Kaffeesatz|s|200 300 400 500 600 700
Noto Sans Display|s|100 200 300 400 500 600 700 800 900
Alata|s|400
Playfair|f|300 400 500 600 700 800 900
Share Tech Mono|m|400
Kumbh Sans|s|100 200 300 400 500 600 700 800 900
Gothic A1|s|100 200 300 400 500 600 700 800 900
Sawarabi Mincho|f|400
Amatic SC|h|400 700
Readex Pro|s|200 300 400 500 600 700
Alegreya|f|400 500 600 700 800 900
Cantarell|s|400 700
Sanchez|f|400
Libre Caslon Text|f|400 700
Patua One|d|400
Noto Sans Devanagari|s|100 200 300 400 500 600 700 800 900
Bangers|d|400
VT323|m|400
Crete Round|f|400
Noto Sans Mono|s|100 200 300 400 500 600 700 800 900
Noto Naskh Arabic|f|400 500 600 700
Changa|s|200 300 400 500 600 700 800
Lexend Giga|s|100 200 300 400 500 600 700 800 900
Fira Code|m|300 400 500 600 700
Oleo Script|d|400 700
Sawarabi Gothic|s|400
Advent Pro|s|100 200 300 400 500 600 700 800 900
Courgette|h|400
Rubik Mono One|s|400
Comic Neue|h|300 400 700
Kaushan Script|h|400
Titan One|d|400
Golos Text|s|400 500 600 700 800 900
League Gothic|s|400
Old Standard TT|f|400 700
Allura|h|400
Sen|s|400 500 600 700 800
Monda|s|400 500 600 700
Biryani|s|200 300 400 600 700 800 900
Sacramento|h|400
Antonio|s|100 200 300 400 500 600 700
Patrick Hand|h|400
Chelsea Market|d|400
Passion One|d|400 700 900
Creepster|d|400
BIZ UDPGothic|s|400 700
Yantramanav|s|100 300 400 500 700 900
Cookie|h|400
Italianno|h|400
Noticia Text|f|400 700
Gruppo|s|400
Signika Negative|s|300 400 500 600 700
Francois One|s|400
Zen Old Mincho|f|400 500 600 700 900
Philosopher|s|400 700
Martel|f|200 300 400 600 700 800 900
Zeyada|h|400
Asap Condensed|s|200 300 400 500 600 700 800 900
Noto Nastaliq Urdu|f|400 500 600 700
Oxanium|d|200 300 400 500 600 700 800
Noto Sans Bengali|s|100 200 300 400 500 600 700 800 900
Josefin Slab|f|100 200 300 400 500 600 700
Actor|s|400
PT Sans Caption|s|400 700
Nanum Gothic Coding|h|400 700
Amaranth|s|400 700
Quattrocento|f|400 700
Mitr|s|200 300 400 500 600 700
Neuton|f|200 300 400 700 800
Rokkitt|f|100 200 300 400 500 600 700 800 900
Encode Sans Condensed|s|100 200 300 400 500 600 700 800 900
Kosugi Maru|s|400
Unica One|d|400
Black Han Sans|s|400
Fugaz One|d|400
Krub|s|200 300 400 500 600 700
Alexandria|s|100 200 300 400 500 600 700 800 900
Rock Salt|h|400
Gilda Display|f|400
Unna|f|400 700
Commissioner|s|100 200 300 400 500 600 700 800 900
Didact Gothic|s|400
Playfair Display SC|f|400 700 900
Gloria Hallelujah|h|400
Berkshire Swash|h|400
Libre Bodoni|f|400 500 600 700
Delius|h|400
Bai Jamjuree|s|200 300 400 500 600 700
Vazirmatn|s|100 200 300 400 500 600 700 800 900
Forum|d|400
Sofia Sans Condensed|s|1 100 200 300 400 500 600 700 800 900 1000
Suez One|f|400
Jura|s|300 400 500 600 700
Paytone One|s|400
Quattrocento Sans|s|400 700
Ubuntu Condensed|s|400
Faustina|f|300 400 500 600 700 800
Rammetto One|d|400
STIX Two Text|f|400 500 600 700
Audiowide|d|400
Concert One|d|400
Andada Pro|f|400 500 600 700 800
Tangerine|h|400 700
M PLUS 1|s|100 200 300 400 500 600 700 800 900
Yeseva One|d|400
Poiret One|d|400
Pinyon Script|h|400
Radio Canada|s|300 400 500 600 700
Monoton|d|400
Playball|d|400
Cinzel Decorative|d|400 700 900
Pathway Gothic One|s|400
Dela Gothic One|d|400
Istok Web|s|400 700
El Messiri|s|400 500 600 700
Chango|d|400
Volkhov|f|400 700
Staatliches|d|400
Gabarito|d|400 500 600 700 800 900
Alex Brush|h|400
Noto Sans Hebrew|s|100 200 300 400 500 600 700 800 900
Google Sans Code|m|300 400 500 600 700 800
Abhaya Libre|f|400 500 600 700 800
PT Mono|m|400
Quantico|s|400 700
Eater|d|400
Architects Daughter|h|400
Arsenal|s|400 700
Lustria|f|400
Hind Guntur|s|300 400 500 600 700
Homemade Apple|h|400
Noto Serif Bengali|f|100 200 300 400 500 600 700 800 900
Lalezar|s|400
Gelasio|f|400 500 600 700
Lusitana|f|400 700
Ubuntu Sans|s|100 200 300 400 500 600 700 800
Goldman|d|400 700
Caveat Brush|h|400
GFS Didot|f|400
Sorts Mill Goudy|f|400
Cormorant Infant|f|300 400 500 600 700
Saira Extra Condensed|s|100 200 300 400 500 600 700 800 900
Ubuntu Mono|m|400 700
Michroma|s|400
Noto Serif Display|f|100 200 300 400 500 600 700 800 900
Parisienne|h|400
Afacad|s|400 500 600 700
Noto Sans Symbols|s|100 200 300 400 500 600 700 800 900
Merienda|h|300 400 500 600 700 800 900
Petrona|f|100 200 300 400 500 600 700 800 900
IBM Plex Sans Thai|s|100 200 300 400 500 600 700
Noto Sans HK|s|100 200 300 400 500 600 700 800 900
Saira Semi Condensed|s|100 200 300 400 500 600 700 800 900
Nanum Pen Script|h|400
Belleza|s|400
Radio Canada Big|s|400 500 600 700
Pragati Narrow|s|400 700
Varela|s|400
Vidaloka|f|400
Noto Sans Malayalam|s|100 200 300 400 500 600 700 800 900
Fira Sans Extra Condensed|s|100 200 300 400 500 600 700 800 900
Reenie Beanie|h|400
Hind Vadodara|s|300 400 500 600 700
Averia Serif Libre|d|300 400 700
Reddit Sans|s|200 300 400 500 600 700 800 900
Dongle|s|300 400 700
Blinker|s|100 200 300 400 600 700 800 900
Besley|f|400 500 600 700 800 900
Alice|f|400
Bad Script|h|400
Fira Mono|m|400 500 700
Calistoga|d|400
Cousine|m|400 700
Cuprum|s|400 500 600 700
Syncopate|s|400 700
Amita|h|400 700
Anonymous Pro|m|400 700
Racing Sans One|d|400
Sofia Sans Extra Condensed|s|1 100 200 300 400 500 600 700 800 900 1000
Jua|s|400
Host Grotesk|s|300 400 500 600 700 800
Six Caps|s|400
Kaisei Decol|f|400 500 700
Carter One|d|400
Mate|f|400
Nothing You Could Do|h|400
Squada One|d|400
Arapey|f|400
Belanosima|s|400 600 700
Bowlby One SC|d|400
Economica|s|400 700
Mada|s|200 300 400 500 600 700 800 900
Pridi|f|200 300 400 500 600 700
Mukta Malar|s|200 300 400 500 600 700 800
Shippori Mincho B1|f|400 500 600 700 800
Ultra|f|400
Mrs Saint Delafield|h|400
Ropa Sans|s|400
Pangolin|h|400
Adamina|f|400
Gochi Hand|h|400
Mona Sans|s|200 300 400 500 600 700 800 900
Taviraj|f|100 200 300 400 500 600 700 800 900
Murecho|s|100 200 300 400 500 600 700 800 900
Handlee|h|400
Khula|s|300 400 600 700 800
Georama|s|100 200 300 400 500 600 700 800 900
Eczar|f|400 500 600 700 800
Cabin Condensed|s|400 500 600 700
Londrina Solid|d|100 300 400 900
Hachi Maru Pop|h|400
Potta One|d|400
Anek Bangla|s|100 200 300 400 500 600 700 800
Julius Sans One|s|400
Sriracha|h|400
Sofia|h|400
Zen Kaku Gothic Antique|s|300 400 500 700 900
Funnel Sans|s|300 400 500 600 700 800
Caprasimo|d|400
Wix Madefor Display|s|400 500 600 700 800
Familjen Grotesk|s|400 500 600 700
M PLUS 2|s|100 200 300 400 500 600 700 800 900
Martel Sans|s|200 300 400 600 700 800 900
Marck Script|h|400
Pirata One|d|400
Leckerli One|h|400
Akshar|s|300 400 500 600 700
Tilt Warp|d|400
Italiana|s|400
Damion|h|400
Gudea|s|400 700
Yrsa|f|300 400 500 600 700
Aboreto|d|400
Chewy|d|400
Mr Dafoe|h|400
IBM Plex Sans JP|s|100 200 300 400 500 600 700
Palanquin|s|100 200 300 400 500 600 700
Basic|s|400
Reem Kufi|s|400 500 600 700
Limelight|d|400
Mandali|s|400
Rye|d|400
Nixie One|d|400
Darker Grotesque|s|300 400 500 600 700 800 900
REM|s|100 200 300 400 500 600 700 800 900
Ovo|f|400
Yuji Mai|f|400
Palanquin Dark|s|400 500 600 700
Lemonada|d|300 400 500 600 700
Jersey 25|d|400
Niramit|s|200 300 400 500 600 700
Alegreya Sans SC|s|100 300 400 500 700 800 900
Covered By Your Grace|h|400
K2D|s|100 200 300 400 500 600 700 800
Carlito|s|400 700
Spline Sans|s|300 400 500 600 700
Cutive Mono|m|400
Tomorrow|s|100 200 300 400 500 600 700 800 900
IM Fell English|f|400
Ruda|s|400 500 600 700 800 900
Bevan|f|400
Parkinsans|s|300 400 500 600 700 800
Electrolize|s|400
Coda|d|400 800
BenchNine|s|300 400 700
MuseoModerno|d|100 200 300 400 500 600 700 800 900
Itim|h|400
UnifrakturMaguntia|d|400
Grandstander|d|100 200 300 400 500 600 700 800 900
Cedarville Cursive|h|400
Charm|h|400 700
Boogaloo|d|400
Red Hat Mono|m|300 400 500 600 700
Charis SIL|f|400 700
Fahkwang|s|200 300 400 500 600 700
Wix Madefor Text|s|400 500 600 700 800
Atkinson Hyperlegible Next|s|200 300 400 500 600 700 800
Just Another Hand|h|400
Ma Shan Zheng|h|400
Big Shoulders|d|100 200 300 400 500 600 700 800 900
Baloo Da 2|d|400 500 600 700 800
Funnel Display|d|300 400 500 600 700 800
Shrikhand|d|400
Skranji|d|400 700
Krona One|s|400
Kiwi Maru|f|300 400 500
Anuphan|s|100 200 300 400 500 600 700
Ms Madi|h|400
Anek Latin|s|100 200 300 400 500 600 700 800
Marcellus SC|f|400
Aldrich|s|400
ZCOOL XiaoWei|s|400
Sansita|s|400 700 800 900
Fustat|s|200 300 400 500 600 700 800
Noto Sans Sinhala|s|100 200 300 400 500 600 700 800 900
Neucha|h|400
Kreon|f|300 400 500 600 700
Gloock|f|400
Rufina|f|400 700
Reddit Sans Condensed|s|200 300 400 500 600 700 800 900
Secular One|s|400
Grenze Gotisch|d|100 200 300 400 500 600 700 800 900
Pontano Sans|s|300 400 500 600 700
Do Hyeon|s|400
Bona Nova SC|f|400 700
Noto Sans Gujarati|s|100 200 300 400 500 600 700 800 900
Andika|s|400 700
Yatra One|d|400
Geo|s|400
Lexend Exa|s|100 200 300 400 500 600 700 800 900
Germania One|d|400
Spinnaker|s|400
Aclonica|s|400
Noto Sans Myanmar|s|100 200 300 400 500 600 700 800 900
Days One|s|400
Balsamiq Sans|d|400 700
Inria Serif|f|300 400 700
Caudex|f|400 700
Nova Square|d|400
Vina Sans|d|400
Judson|f|400 700
ADLaM Display|d|400
Livvic|s|100 200 300 400 500 600 700 900
Athiti|s|200 300 400 500 600 700
Rozha One|f|400
Tiro Bangla|f|400
Bellefair|f|400
Libre Barcode 128|d|400
Shadows Into Light Two|h|400
Castoro|f|400
Special Gothic Expanded One|s|400
La Belle Aurore|h|400
Glory|s|100 200 300 400 500 600 700 800
Sofia Sans Semi Condensed|s|1 100 200 300 400 500 600 700 800 900 1000
Gowun Batang|f|400 700
Herr Von Muellerhoff|h|400
Bowlby One|d|400
Stardos Stencil|d|400 700
Podkova|f|400 500 600 700 800
Fondamento|h|400
Proza Libre|s|400 500 600 700 800
Sintony|s|400 700
Uncial Antiqua|d|400
Cormorant Upright|f|300 400 500 600 700
Seaweed Script|d|400
PT Serif Caption|f|400
Glegoo|f|400 700
Pixelify Sans|d|400 500 600 700
Oranienbaum|f|400
Laila|f|300 400 500 600 700
Libre Caslon Display|f|400
Radley|f|400
Barriecito|d|400
Oooh Baby|h|400
Trirong|f|100 200 300 400 500 600 700 800 900
AR One Sans|s|400 500 600 700
Fredericka the Great|d|400
DotGothic16|s|400
Overpass Mono|m|300 400 500 600 700
Gantari|s|100 200 300 400 500 600 700 800 900
Gabriela|f|400
Corben|d|400 700
Metrophobic|s|400
BIZ UDGothic|s|400 700
Protest Revolution|d|400
Averia Libre|d|300 400 700
ZCOOL KuaiLe|s|400
Cabin Sketch|d|400 700
Tektur|d|400 500 600 700 800 900
Elsie|d|400 900
Pathway Extreme|s|100 200 300 400 500 600 700 800 900
Graduate|f|400
Niconne|h|400
Candal|s|400
Fragment Mono|m|400
Klee One|h|400 600
Tiro Devanagari Hindi|f|400
Noto Serif Georgian|f|100 200 300 400 500 600 700 800 900
Aguafina Script|h|400
Noto Sans Kannada|s|100 200 300 400 500 600 700 800 900
Kameron|f|400 500 600 700
Afacad Flux|s|100 200 300 400 500 600 700 800 900 1000
Lateef|f|200 300 400 500 600 700 800
Hina Mincho|f|400
Karma|f|300 400 500 600 700
Allison|h|400
Rampart One|d|400
Sarala|s|400 700
Ibarra Real Nova|f|400 500 600 700
Knewave|d|400
Kosugi|s|400
Cantata One|f|400
IM Fell English SC|f|400
IBM Plex Sans KR|s|100 200 300 400 500 600 700
Chonburi|d|400
Telex|s|400
Wallpoet|d|400
Mochiy Pop One|s|400
Yesteryear|h|400
Nobile|s|400 500 700
Pattaya|s|400
Markazi Text|f|400 500 600 700
STIX Two Math|f|400
Fjord One|f|400
Noto Sans Meetei Mayek|s|100 200 300 400 500 600 700 800 900
Petit Formal Script|h|400
Mali|h|200 300 400 500 600 700
Alef|s|400 700
Pompiere|d|400
Noto Sans Gurmukhi|s|100 200 300 400 500 600 700 800 900
Armata|s|400
Style Script|h|400
Share|s|400 700
Nanum Brush Script|h|400
Chivo Mono|m|100 200 300 400 500 600 700 800 900
Cormorant SC|f|300 400 500 600 700
Hepta Slab|f|1 100 200 300 400 500 600 700 800 900
Brygada 1918|f|400 500 600 700
Honk|d|400
Encode Sans Expanded|s|100 200 300 400 500 600 700 800 900
Antic Didone|f|400
BIZ UDPMincho|f|400 700
Arizonia|h|400
Allerta Stencil|s|400
Trocchi|f|400
RocknRoll One|s|400
Major Mono Display|m|400
Alegreya SC|f|400 500 700 800 900
Lexend Zetta|s|100 200 300 400 500 600 700 800 900
Sedgwick Ave Display|h|400
Cal Sans|s|400
Azeret Mono|m|100 200 300 400 500 600 700 800 900
Noto Sans Oriya|s|100 200 300 400 500 600 700 800 900
Playpen Sans|h|100 200 300 400 500 600 700 800
Annie Use Your Telescope|h|400
Noto Sans Georgian|s|100 200 300 400 500 600 700 800 900
Grand Hotel|h|400
Monsieur La Doulaise|h|400
Silkscreen|d|400 700
Enriqueta|f|400 500 600 700
TikTok Sans|s|300 400 500 600 700 800 900
Amiko|s|400 600 700
Yusei Magic|s|400
Monomaniac One|s|400
Goudy Bookletter 1911|f|400
Koulen|d|400
Baloo Thambi 2|d|400 500 600 700 800
Irish Grover|d|400
Average Sans|s|400
Alatsi|s|400
Bellota Text|d|300 400 700
Caladea|f|400 700
Zalando Sans|s|200 300 400 500 600 700 800 900
Allerta|s|400
Flow Circular|d|400
Noto Serif Devanagari|f|100 200 300 400 500 600 700 800 900
Schoolbell|h|400
Bentham|f|400
Sniglet|d|400 800
Arbutus Slab|f|400
Norican|h|400
Halant|f|300 400 500 600 700
Ruslan Display|d|400
Rosario|s|300 400 500 600 700
Rancho|h|400
Overlock|d|400 700 900
Ephesis|h|400
Faster One|d|400
Kdam Thmor Pro|s|400
Poller One|d|400
Almendra|f|400 700
Marvel|s|400 700
Kristi|h|400
Mouse Memoirs|s|400
Rakkas|d|400
Spline Sans Mono|m|300 400 500 600 700
Calligraffitti|h|400
Bayon|s|400
Turret Road|d|200 300 400 500 700 800
Chiron GoRound TC|s|200 300 400 500 600 700 800 900
Coming Soon|h|400
Sigmar One|d|400
Mansalva|h|400
Dawning of a New Day|h|400
Montagu Slab|f|100 200 300 400 500 600 700
Rambla|s|400 700
Marmelad|s|400
BioRhyme|f|200 300 400 500 600 700 800
Poetsen One|d|400
Lekton|m|400 700
Young Serif|f|400
Scada|s|400 700
Meddon|h|400
Sansita Swashed|d|300 400 500 600 700 800 900
Recursive|s|300 400 500 600 700 800 900 1000
Special Gothic Condensed One|s|400
Kantumruy Pro|s|100 200 300 400 500 600 700
Love Ya Like A Sister|d|400
Anton SC|s|400
Square Peg|h|400
DynaPuff|d|400 500 600 700
Croissant One|d|400
Average|f|400
Bubblegum Sans|d|400
Kurale|f|400
Cairo Play|s|200 300 400 500 600 700 800 900 1000
Hahmlet|f|100 200 300 400 500 600 700 800 900
Spectral SC|f|200 300 400 500 600 700 800
Manjari|s|100 400 700
Inria Sans|s|300 400 700
Zen Antique|f|400
Slackey|d|400
Corinthia|h|400 700
Bungee Inline|d|400
Hanuman|f|100 200 300 400 500 600 700 800 900
Akatab|s|400 500 600 700 800 900
Fanwood Text|f|400
Kadwa|f|400 700
Maitree|f|200 300 400 500 600 700
Aref Ruqaa|f|400 700
Waiting for the Sunrise|h|400
Qwitcher Grypen|h|400 700
Contrail One|d|400
Frijole|d|400
Over the Rainbow|h|400
Agbalumo|d|400
Baloo Bhaijaan 2|d|400 500 600 700 800
David Libre|f|400 500 700
Lexend Peta|s|100 200 300 400 500 600 700 800 900
Sometype Mono|m|400 500 600 700
Delius Unicase|h|400 700
Metamorphous|d|400
Special Gothic|s|400 500 600 700
IBM Plex Sans Hebrew|s|100 200 300 400 500 600 700
Rubik Doodle Shadow|d|400
Oxygen Mono|m|400
Noto Emoji|s|300 400 500 600 700
Mountains of Christmas|d|400 700
ZCOOL QingKe HuangYou|s|400
MedievalSharp|d|400
Gowun Dodum|s|400
Noto Sans Ol Chiki|s|400 500 600 700
Mukta Mahee|s|200 300 400 500 600 700 800
Zen Kurenaido|s|400
Copse|f|400
Magra|s|400 700
Battambang|d|100 300 400 700 900
Red Rose|d|300 400 500 600 700
Yuji Syuku|f|400
Syne Mono|m|400
Vesper Libre|f|400 500 700 900
Kalnia|f|100 200 300 400 500 600 700
Baloo Bhai 2|d|400 500 600 700 800
Cormorant Unicase|f|300 400 500 600 700
Cambay|s|400 700
Boldonse|d|400
Anek Devanagari|s|100 200 300 400 500 600 700 800
Alike|f|400
Rochester|h|400
Rouge Script|h|400
Beth Ellen|h|400
Kaisei Opti|f|400 500 700
Encode Sans Semi Condensed|s|100 200 300 400 500 600 700 800 900
Anybody|d|100 200 300 400 500 600 700 800 900
Libre Barcode 39 Text|d|400
Fasthand|d|400
Bagel Fat One|d|400
Kodchasan|s|200 300 400 500 600 700
Meow Script|h|400
Sunflower|s|300 500 700
Birthstone|h|400
Platypi|f|300 400 500 600 700 800
Hurricane|h|400
Zen Dots|d|400
Codystar|d|300 400
Scheherazade New|f|400 500 600 700
IM Fell DW Pica|f|400
Jockey One|s|400
Baloo Chettan 2|d|400 500 600 700 800
Hedvig Letters Serif|f|400
Happy Monkey|d|400
Cutive|f|400
KoHo|s|200 300 400 500 600 700
Tilt Neon|d|400
Amarante|d|400
Bungee Spice|d|400
Bungee Shade|d|400
Zalando Sans Expanded|s|200 300 400 500 600 700 800 900
Baloo Tamma 2|d|400 500 600 700 800
Shantell Sans|d|300 400 500 600 700 800
Quintessential|h|400
Henny Penny|d|400
Zain|s|200 300 400 700 800 900
Asar|f|400
Zen Antique Soft|f|400
Gaegu|h|300 400 700
SUSE|s|100 200 300 400 500 600 700 800 900
Coustard|f|400 900
Zalando Sans SemiExpanded|s|200 300 400 500 600 700 800 900
Rasa|f|300 400 500 600 700
Carrois Gothic|s|400
Capriola|s|400
Prosto One|d|400
Poly|f|400
Vibur|h|400
Walter Turncoat|h|400
Tenali Ramakrishna|s|400
Gotu|s|400
Ysabeau Office|s|1 100 200 300 400 500 600 700 800 900 1000
Asul|f|400 700
Averia Sans Libre|d|300 400 700
Encode Sans Semi Expanded|s|100 200 300 400 500 600 700 800 900
Teachers|s|400 500 600 700 800
Stick No Bills|s|200 300 400 500 600 700 800
Megrim|d|400
Noto Sans Symbols 2|s|400
Qwigley|h|400
Puritan|s|400 700
Sue Ellen Francisco|h|400
Rubik Spray Paint|d|400
Arima|d|100 200 300 400 500 600 700
Inknut Antiqua|f|300 400 500 600 700 800 900
Vast Shadow|f|400
Noto Serif Thai|f|100 200 300 400 500 600 700 800 900
Piazzolla|f|100 200 300 400 500 600 700 800 900
Give You Glory|h|400
Jaldi|s|400 700
Voltaire|s|400
Lily Script One|d|400
Coiny|d|400
Fauna One|f|400
Fontdiner Swanky|d|400
Noto Sans Armenian|s|100 200 300 400 500 600 700 800 900
Crafty Girls|h|400
Nosifer|d|400
Oleo Script Swash Caps|d|400 700
Shippori Antique|s|400
Supermercado One|d|400
Brawler|f|400 700
Noto Sans Thai Looped|s|100 200 300 400 500 600 700 800 900
Quando|f|400
Martian Mono|m|100 200 300 400 500 600 700 800
Miriam Libre|s|400 500 600 700
Finger Paint|d|400
Numans|s|400
Nova Mono|m|400
Cherry Bomb One|d|400
Cherry Cream Soda|d|400
Comic Relief|d|400 700
Antic|s|400
Della Respira|f|400
Noto Sans Warang Citi|s|400
Inclusive Sans|s|300 400 500 600 700
Rubik Dirt|d|400
Denk One|s|400
Allan|d|400 700
Xanh Mono|m|400
McLaren|d|400
MonteCarlo|h|400
Euphoria Script|h|400
Port Lligat Sans|s|400
Buenard|f|400 500 600 700
Kelly Slab|d|400
B612 Mono|m|400 700
Abyssinica SIL|f|400
Song Myung|f|400
Vollkorn SC|f|400 600 700 900
Kaisei Tokumin|f|400 500 700 800
Jomhuria|d|400
Moon Dance|h|400
Tienne|f|400 700 900
Bakbak One|d|400
Slabo 13px|f|400
Mohave|s|300 400 500 600 700
Freeman|d|400
Aladin|d|400
Expletus Sans|d|400 500 600 700
Nerko One|h|400
Nata Sans|s|100 200 300 400 500 600 700 800 900
Anta|s|400
Gurajada|s|400
Balthazar|f|400
Oregano|d|400
Rubik Glitch|d|400
Kufam|s|400 500 600 700 800 900
Lacquer|d|400
Macondo|d|400
Montez|h|400
Doppio One|s|400
Padauk|s|400 700
Noto Serif Tamil|f|100 200 300 400 500 600 700 800 900
Mr De Haviland|h|400
Road Rage|d|400
Protest Strike|d|400
Mukta Vaani|s|200 300 400 500 600 700 800
B612|s|400 700
League Script|h|400
Vujahday Script|h|400
Freehand|d|400
IM Fell Double Pica|f|400
Gamja Flower|h|400
Sarina|d|400
Fresca|s|400
Voces|s|400
Unkempt|d|400 700
Kranky|d|400
Griffy|d|400
Carattere|h|400
Molengo|s|400
Alike Angular|f|400
Arya|s|400 700
Noto Sans Ethiopic|s|100 200 300 400 500 600 700 800 900
Suranna|f|400
New Rocker|d|400
Thasadith|s|400 700
Bigshot One|d|400
The Girl Next Door|h|400
Sunshiney|h|400
Aoboshi One|f|400
Julee|h|400
Jolly Lodger|d|400
Zhi Mang Xing|h|400
Loved by the King|h|400
Ceviche One|d|400
Whisper|h|400
Sansation|s|300 400 700
Redressed|h|400
Holtwood One SC|f|400
Fuggles|h|400
Fleur De Leah|h|400
Bilbo Swash Caps|h|400
Freckle Face|d|400
Modak|d|400
Solway|f|300 400 500 700 800
Sarpanch|s|400 500 600 700 800 900
Meie Script|h|400
Farro|s|300 400 500 700
Iceberg|d|400
Cambo|f|400
Orelega One|d|400
Fuzzy Bubbles|h|400 700
Noto Sans Lao|s|100 200 300 400 500 600 700 800 900
Patrick Hand SC|h|400
Charmonman|h|400 700
Grenze|f|100 200 300 400 500 600 700 800 900
Asset|d|400
Bonheur Royale|h|400
Mako|s|400
Sulphur Point|s|300 400 700
Trade Winds|d|400
Wendy One|s|400
Inder|s|400
Nokora|s|100 200 300 400 500 600 700 800 900
Lancelot|d|400
Goblin One|d|400
Modern Antiqua|d|400
Poltawski Nowy|f|400 500 600 700
Libertinus Serif|f|400 600 700
Mallanna|s|400
Scope One|f|400
Federo|s|400
Madimi One|s|400
Imprima|s|400
Wire One|s|400
Metal Mania|d|400
Jersey 10|d|400
Bellota|d|300 400 700
Atma|d|300 400 500 600 700
Galada|d|400
Nova Flat|d|400
Anek Tamil|s|100 200 300 400 500 600 700 800
Libre Barcode 39 Extended Text|d|400
Anek Malayalam|s|100 200 300 400 500 600 700 800
UnifrakturCook|d|700
Mina|s|400 700
BhuTuka Expanded One|f|400
Rosarivo|f|400
Doto|s|100 200 300 400 500 600 700 800 900
Artifika|f|400
Prociono|f|400
Viaoda Libre|d|400
Moul|d|400
Mooli|s|400
Chathura|s|100 300 400 700 800
Baloo Paaji 2|d|400 500 600 700 800
Sekuya|d|400
Just Me Again Down Here|h|400
Long Cang|h|400
Nova Round|d|400
Amethysta|f|400
Sancreek|d|400
Odibee Sans|d|400
Bruno Ace|d|400
Darumadrop One|d|400
Shanti|s|400
Crushed|d|400
WindSong|h|400 500
Noto Serif Khojki|f|400 500 600 700
Esteban|f|400
Bona Nova|f|400 700
Ysabeau SC|s|1 100 200 300 400 500 600 700 800 900 1000
Libertinus Math|d|400
Maiden Orange|f|400
Dynalight|d|400
Mirza|f|400 500 600 700
Mochiy Pop P One|s|400
Monofett|m|400
Poor Story|d|400
Sour Gummy|s|100 200 300 400 500 600 700 800 900
IM Fell French Canon|f|400
Asta Sans|s|300 400 500 600 700 800
Reggae One|d|400
Convergence|s|400
Anaheim|s|400 500 600 700 800
Sail|d|400
Life Savers|d|400 700 800
Swanky and Moo Moo|h|400
Carme|s|400
Sedgwick Ave|h|400
Gayathri|s|100 400 700
Ribeye|d|400
Montaga|f|400
Delicious Handrawn|h|400
Noto Serif HK|f|200 300 400 500 600 700 800 900
Truculenta|s|100 200 300 400 500 600 700 800 900
Science Gothic|s|100 200 300 400 500 600 700 800 900
Alan Sans|s|300 400 500 600 700 800 900
Original Surfer|d|400
Sevillana|d|400
Manuale|f|300 400 500 600 700 800
Delius Swash Caps|h|400
Medula One|d|400
Gluten|d|100 200 300 400 500 600 700 800 900
Yomogi|h|400
Train One|d|400
Kablammo|d|400
NTR|s|400
Gentium Book Plus|f|400 700
Comme|s|100 200 300 400 500 600 700 800 900
Atomic Age|d|400
Shojumaru|d|400
Qahiri|s|400
M PLUS 1 Code|m|100 200 300 400 500 600 700
Karantina|d|300 400 700
Borel|h|400
Smythe|d|400
Salsa|d|400
Galindo|d|400
Baloo Tammudu 2|d|400 500 600 700 800
Belgrano|f|400
Orienta|s|400
Ledger|f|400
Cherry Swash|d|400 700
Peralta|f|400
Phudu|d|300 400 500 600 700 800 900
The Nautigal|h|400 700
Birthstone Bounce|h|400 500
Baumans|d|400
Hi Melody|h|400
IM Fell Great Primer|f|400
Waterfall|h|400
Iceland|d|400
Genos|s|100 200 300 400 500 600 700 800 900
Gupter|f|400 500 700
Dokdo|d|400
Gasoek One|s|400
IM Fell DW Pica SC|f|400
Imperial Script|h|400
Stalemate|h|400
Kavoon|d|400
Mozilla Headline|s|200 300 400 500 600 700
Protest Riot|d|400
Alkatra|d|400 500 600 700
Nova Oval|d|400
Reddit Mono|m|200 300 400 500 600 700 800 900
Stick|s|400
Jacques Francois|f|400
Imbue|f|100 200 300 400 500 600 700 800 900
Emilys Candy|d|400
Clicker Script|h|400
Overlock SC|d|400
Edu TAS Beginner|h|400 500 600 700
IBM Plex Sans Thai Looped|s|100 200 300 400 500 600 700
Notable|s|400
Solitreo|h|400
Liu Jian Mao Cao|h|400
Rubik Bubbles|d|400
Sumana|f|400 700
Lemon|d|400
Ysabeau|s|1 100 200 300 400 500 600 700 800 900 1000
Sigmar|d|400
Victor Mono|m|100 200 300 400 500 600 700
Caesar Dressing|d|400
Chau Philomene One|s|400
Gugi|d|400
Luxurious Script|h|400
Duru Sans|s|400
Miltonian|d|400
Bitcount Single|d|100 200 300 400 500 600 700 800 900
IM Fell Double Pica SC|f|400
Gentium Plus|f|400 700
Kenia|d|400
Nova Slim|d|400
Suwannaphum|f|100 300 400 700 900
Harmattan|s|400 500 600 700
Agdasima|s|400 700
Chicle|d|400
Sree Krushnadevaraya|f|400
Badeen Display|d|400
Spicy Rice|d|400
Bokor|d|400
Akronim|d|400
Raleway Dots|d|400
Moderustic|s|300 400 500 600 700 800
Tauri|s|400
Rationale|s|400
Homenaje|s|400
Eagle Lake|h|400
Timmana|s|400
Elms Sans|s|100 200 300 400 500 600 700 800 900
Baloo Bhaina 2|d|400 500 600 700 800
Headland One|f|400
Licorice|h|400
Edu SA Beginner|h|400 500 600 700
Kode Mono|m|400 500 600 700
Gafata|s|400
Noto Serif Telugu|f|100 200 300 400 500 600 700 800 900
Kotta One|f|400
Ranchers|d|400
Ruthie|h|400
Noto Sans Bhaiksuki|s|400
IM Fell French Canon SC|f|400
Noto Serif Kannada|f|100 200 300 400 500 600 700 800 900
Fenix|f|400
BIZ UDMincho|f|400 700
Inika|f|400 700
Mynerve|h|400
Baskervville SC|f|400 500 600 700
IM Fell Great Primer SC|f|400
Alkalami|f|400
TASA Orbiter|s|400 500 600 700 800
Short Stack|h|400
Astloch|d|400 700
Anek Gujarati|s|100 200 300 400 500 600 700 800
Trispace|s|100 200 300 400 500 600 700 800
Gemunu Libre|s|200 300 400 500 600 700 800
Akaya Kanadaka|d|400
Fascinate|d|400
Miniver|d|400
Hubot Sans|s|200 300 400 500 600 700 800 900
Londrina Outline|d|400
Kulim Park|s|200 300 400 600 700
Jomolhari|f|400
Habibi|f|400
Comforter|h|400
Anek Kannada|s|100 200 300 400 500 600 700 800
Varta|s|300 400 500 600 700
Khmer|s|400
Faculty Glyphic|s|400
Miltonian Tattoo|d|400
East Sea Dokdo|h|400
Nova Cut|d|400
Stint Ultra Condensed|f|400
Beau Rivage|h|400
Edu NSW ACT Cursive|h|400 500 600 700
Macondo Swash Caps|d|400
Stack Sans Text|s|200 300 400 500 600 700
Vampiro One|d|400
Hedvig Letters Sans|s|400
Noto Sans Caucasian Albanian|s|400
Dangrek|d|400
Libre Barcode 128 Text|d|400
Mystery Quest|d|400
IBM Plex Sans Devanagari|s|100 200 300 400 500 600 700
Ballet|h|400
Noto Serif Hebrew|f|100 200 300 400 500 600 700 800 900
Nova Script|d|400
Noto Serif Malayalam|f|100 200 300 400 500 600 700 800 900
Bitcount Prop Single|d|100 200 300 400 500 600 700 800 900
Redacted|d|400
Geostar Fill|d|400
Gorditas|d|400 700
Katibeh|d|400
Dorsa|s|400
Pavanam|s|400
Stoke|f|300 400
Jaro|s|400
Winky Sans|s|300 400 500 600 700 800 900
Libertinus Sans|s|400 700
Mozilla Text|s|200 300 400 500 600 700
Stylish|s|400
Playwrite NO|h|100 200 300 400
Margarine|d|400
Smooch|h|400
Mea Culpa|h|400
Noto Sans Canadian Aboriginal|s|100 200 300 400 500 600 700 800 900
Liter|s|400
Tiny5|s|400
Risque|d|400
Bodoni Moda SC|f|400 500 600 700 800 900
Single Day|d|400
Lugrasimo|h|400
Nabla|d|400
Stack Sans Headline|s|200 300 400 500 600 700
Zen Tokyo Zoo|d|400
LXGW WenKai TC|h|300 400 700
Chocolate Classical Sans|s|400
Braah One|s|400
Lavishly Yours|h|400
Lovers Quarrel|h|400
Underdog|d|400
Barrio|d|400
Island Moments|h|400
Passions Conflict|h|400
Devonshire|h|400
Junge|f|400
Jacquard 12|d|400
Mate SC|f|400
Sura|f|400 700
Koh Santepheap|f|100 300 400 700 900
Shippori Antique B1|s|400
Playpen Sans Arabic|h|100 200 300 400 500 600 700 800
Englebert|s|400
Noto Sans Thaana|s|100 200 300 400 500 600 700 800 900
Zilla Slab Highlight|f|400 700
Akaya Telivigala|d|400
Rum Raisin|s|400
Playwrite US Trad|h|100 200 300 400
Kavivanar|h|400
Amiri Quran|f|400
Cagliostro|s|400
Noto Sans Math|s|400
Strait|s|400
Noto Sans Javanese|s|400 500 600 700
Glass Antiqua|d|400
Playwrite VN|h|100 200 300 400
Dai Banna SIL|f|300 400 500 600 700
Noto Sans Khudawadi|s|400
Engagement|h|400
Grape Nuts|h|400
Yuji Boku|f|400
Manufacturing Consent|d|400
Playwrite IN|h|100 200 300 400
Beiruti|s|200 300 400 500 600 700 800 900
Odor Mean Chey|f|400
Paprika|d|400
Spirax|d|400
Rubik Scribble|d|400
Romanesco|h|400
Port Lligat Slab|f|400
Yeon Sung|d|400
Montserrat Underline|s|100 200 300 400 500 600 700 800 900
Cactus Classical Serif|f|400
Caramel|h|400
Noto Music|s|400
Smokum|d|400
Story Script|s|400
Joan|f|400
Festive|h|400
Marhey|d|300 400 500 600 700
Cute Font|d|400
Cantora One|s|400
Tac One|s|400
Text Me One|s|400
Nuosu SIL|s|400
Unlock|d|400
Geom|s|300 400 500 600 700 800 900
Lexend Mega|s|100 200 300 400 500 600 700 800 900
Huninn|s|400
Seymour One|s|400
Playwrite DE Grund|h|100 200 300 400
Noto Sans Samaritan|s|400
Kapakana|h|300 400
Noto Sans Tagalog|s|400
Noto Sans Buhid|s|400
Srisakdi|d|400 700
Piedra|d|400
Noto Sans Linear A|s|400
Sono|s|200 300 400 500 600 700 800
Diphylleia|f|400
Arbutus|f|400
Noto Serif Khmer|f|100 200 300 400 500 600 700 800 900
Linden Hill|f|400
Dekko|h|400
Content|d|400 700
Girassol|d|400
Orbit|s|400
Tourney|d|100 200 300 400 500 600 700 800 900
Castoro Titling|d|400
New Tegomin|f|400
Bilbo|h|400
Water Brush|h|400
Kaisei HarunoUmi|f|400 500 700
Playwrite IS|h|100 200 300 400
Siemreap|s|400
Shalimar|h|400
Texturina|f|100 200 300 400 500 600 700 800 900
Handjet|d|100 200 300 400 500 600 700 800 900
Gulzar|f|400
Playwrite CU|h|100 200 300 400
Sonsie One|d|400
SN Pro|s|200 300 400 500 600 700 800 900
Carrois Gothic SC|s|400
Noto Serif Tibetan|f|100 200 300 400 500 600 700 800 900
Climate Crisis|d|400
Erica One|d|400
Flamenco|d|300 400
Playwrite DE SAS Guides|h|400
Momo Trust Sans|s|200 300 400 500 600 700 800
BBH Bartle|s|400
Tillana|d|400 500 600 700 800
Tiro Devanagari Sanskrit|f|400
Tiro Gurmukhi|f|400
Encode Sans SC|s|100 200 300 400 500 600 700 800 900
Simonetta|d|400 900
Almendra SC|f|400
Sahitya|f|400 700
Reem Kufi Fun|s|400 500 600 700
Dhurjati|s|400
Playwrite DE LA Guides|h|400
Felipa|h|400
Anek Odia|s|100 200 300 400 500 600 700 800
Edu AU VIC WA NT Guides|h|400 500 600 700
Yaldevi|s|200 300 400 500 600 700
WDXL Lubrifont JP N|s|400
Emblema One|d|400
Rubik Moonrocks|d|400
Gwendolyn|h|400 700
Alumni Sans Pinstripe|s|400
Stint Ultra Expanded|f|400
Condiment|h|400
Ysabeau Infant|s|1 100 200 300 400 500 600 700 800 900 1000
Ramaraja|f|400
Ravi Prakash|d|400
Autour One|d|400
Noto Serif Ahom|f|400
Jim Nightshade|h|400
National Park|s|200 300 400 500 600 700 800
Mogra|d|400
Ewert|d|400
Rubik Wet Paint|d|400
Ancizar Serif|f|300 400 500 600 700 800 900
Keania One|d|400
My Soul|h|400
Offside|d|400
Monomakh|d|400
Jersey 20|d|400
Playwrite GB S|h|100 200 300 400
Big Shoulders Stencil|d|100 200 300 400 500 600 700 800 900
Londrina Shadow|d|400
Kite One|s|400
Butcherman|d|400
Milonga|d|400
Slackside One|h|400
Tilt Prism|d|400
Noto Serif Armenian|f|100 200 300 400 500 600 700 800 900
Bruno Ace SC|d|400
Joti One|d|400
Noto Sans Osmanya|s|400
Cascadia Code|s|200 300 400 500 600 700
Vend Sans|s|300 400 500 600 700
Chela One|d|400
Federant|d|400
Farsan|d|400
Playwrite AU NSW|h|100 200 300 400
Comforter Brush|h|400
Plaster|d|400
Jacquarda Bastarda 9|d|400
Buda|d|300
Purple Purse|d|400
Bpmf Huninn|s|400
Tiro Devanagari Marathi|f|400
Averia Gruesa Libre|d|400
Alyamama|f|300 400 500 600 700 800 900
Lexend Tera|s|100 200 300 400 500 600 700 800 900
Bungee Outline|d|400
Donegal One|f|400
Fruktur|d|400
Benne|f|400
Momo Trust Display|s|400
Wellfleet|f|400
Marko One|f|400
SUSE Mono|s|100 200 300 400 500 600 700 800
Libre Barcode EAN13 Text|d|400
Chiron Hei HK|s|200 300 400 500 600 700 800 900
Akt|s|100 200 300 400 500 600 700 800 900
Trykker|f|400
Alumni Sans SC|s|100 200 300 400 500 600 700 800 900
GFS Neohellenic|s|400 700
Elsie Swash Caps|d|400 900
Preahvihear|s|400
Praise|h|400
Galdeano|s|400
Atkinson Hyperlegible Mono|s|200 300 400 500 600 700 800
Noto Sans Sora Sompeng|s|400 500 600 700
Noto Sans Gothic|s|400
Bungee Hairline|d|400
Sixtyfour|m|400
Chilanka|h|400
Jacques Francois Shadow|d|400
Luxurious Roman|d|400
Oldenburg|d|400
Gidugu|s|400
Blaka|d|400
Sofadi One|d|400
Fascinate Inline|d|400
Almendra Display|d|400
Kings|h|400
Diplomata|d|400
Metal|d|400
Anek Gurmukhi|s|100 200 300 400 500 600 700 800
Bubbler One|s|400
Ruluko|s|400
Edu AU VIC WA NT Hand|h|400 500 600 700
Kirang Haerang|d|400
Babylonica|h|400
Uchen|f|400
Sirin Stencil|d|400
Noto Sans Tai Viet|s|400
Noto Serif Gujarati|f|100 200 300 400 500 600 700 800 900
Noto Serif Lao|f|100 200 300 400 500 600 700 800 900
Alumni Sans Inline One|d|400
Aref Ruqaa Ink|f|400 700
Grechen Fuemen|h|400
Hubballi|s|400
Alumni Sans Collegiate One|s|400
Libre Barcode 39 Extended|d|400
Bigelow Rules|d|400
Inspiration|h|400
Lakki Reddy|h|400
Grey Qo|h|400
Jersey 15|d|400
New Amsterdam|s|400
Ranga|d|400 700
Revalia|d|400
Wittgenstein|f|400 500 600 700 800 900
Tulpen One|d|400
Gideon Roman|d|400
Bitcount Grid Double|d|100 200 300 400 500 600 700 800 900
Dr Sugiyama|h|400
Oi|d|400
Noto Sans Adlam|s|400 500 600 700
Rhodium Libre|f|400
Are You Serious|h|400
Playwrite VN Guides|h|400
Lunasima|s|400 700
Playwrite AU SA|h|100 200 300 400
Noto Serif Sinhala|f|100 200 300 400 500 600 700 800 900
Edu VIC WA NT Beginner|h|400 500 600 700
Jacquard 24|d|400
Noto Sans Cherokee|s|100 200 300 400 500 600 700 800 900
Sedan SC|f|400
Neonderthaw|h|400
Noto Sans Glagolitic|s|400
Tiro Kannada|f|400
Stalinist One|d|400
Miss Fajardose|h|400
Noto Sans Lao Looped|s|100 200 300 400 500 600 700 800 900
Ribeye Marrow|d|400
Updock|h|400
Bacasime Antique|f|400
Noto Sans Elbasan|s|400
Momo Signature|s|400
Arsenal SC|s|400 700
Noto Sans Anatolian Hieroglyphs|s|400
Meera Inimai|s|400
Kumar One|d|400
Reem Kufi Ink|s|400
Love Light|h|400
Diplomata SC|d|400
Foldit|d|100 200 300 400 500 600 700 800 900
Geist Pixel|d|400
Micro 5|d|400
Noto Rashi Hebrew|f|100 200 300 400 500 600 700 800 900
WDXL Lubrifont SC|s|400
LXGW WenKai Mono TC|m|300 400 700
Intel One Mono|m|300 400 500 600 700
Epunda Sans|s|300 400 500 600 700 800 900
Passero One|d|400
Tiro Telugu|f|400
Tsukimi Rounded|s|300 400 500 600 700
Send Flowers|h|400
Konkhmer Sleokchher|d|400
Londrina Sketch|d|400
Trochut|d|400 700
Rubik Pixels|d|400
Rubik Distressed|d|400
Playwrite IE|h|100 200 300 400
Bahiana|d|400
Big Shoulders Inline|d|100 200 300 400 500 600 700 800 900
Ponomar|d|400
Rubik Iso|d|400
TASA Explorer|s|400 500 600 700 800
Playwrite US Modern|h|100 200 300 400
Noto Sans Syloti Nagri|s|400
Edu NSW ACT Foundation|h|400 500 600 700
Mr Bedfort|h|400
Noto Sans Tangsa|s|400 500 600 700
Rubik Glitch Pop|d|400
Ubuntu Sans Mono|m|400 500 600 700
Stack Sans Notch|s|200 300 400 500 600 700
Ancizar Sans|s|100 200 300 400 500 600 700 800 900 1000
Triodion|d|400
Cause|h|100 200 300 400 500 600 700 800 900
BioRhyme Expanded|f|200 300 400 700 800
Cossette Texte|s|400 700
Bonbon|h|400
Kedebideri|s|400 500 600 700 800 900
Princess Sofia|h|400
Flavors|d|400
Chenla|d|400
Hanalei Fill|d|400
Shizuru|d|400
Gidole|s|400
Kumar One Outline|d|400
Peddana|f|400
Noto Serif Ethiopic|f|100 200 300 400 500 600 700 800 900
Noto Sans Batak|s|400
Mrs Sheppards|h|400
Sixtyfour Convergence|m|400
Gajraj One|d|400
Noto Sans Balinese|s|400 500 600 700
Noto Sans Mongolian|s|400
Twinkle Star|h|400
Playwrite HR|h|100 200 300 400
Rubik Vinyl|d|400
Black And White Picture|d|400
Sedan|f|400
Rubik Burned|d|400
Pliant|s|100 200 300 400 500 600 700 800 900
Snippet|s|400
Kolker Brush|h|400
Noto Sans Old Hungarian|s|400
Splash|h|400
Amarna|s|100 200 300 400 500 600 700
Cossette Titre|s|400 700
Lumanosimo|h|400
Molle|h|
Playwrite BR Guides|h|400
Playwrite RO|h|100 200 300 400
Vibes|d|400
Iosevka Charon|m|300 400 500 700
Bitcount Grid Single|d|100 200 300 400 500 600 700 800 900
Playwrite AU QLD|h|100 200 300 400
Iansui|h|400
Rubik Gemstones|d|400
Gveret Levin|h|400
Workbench|m|400
Noto Sans Kaithi|s|400
Noto Sans Cypro Minoan|s|400
Playwrite AT|h|100 200 300 400
Edu AU VIC WA NT Dots|h|400 500 600 700
Aubrey|d|400
Noto Sans Coptic|s|400
Noto Serif Yezidi|f|400 500 600 700
Cascadia Mono|s|200 300 400 500 600 700
Ojuju|s|200 300 400 500 600 700 800
Tiro Tamil|f|400
Parastoo|f|400 500 600 700
Ole|h|400
Chiron Sung HK|f|200 300 400 500 600 700 800 900
Protest Guerrilla|d|400
Playwrite DK Uloopet|h|100 200 300 400
Libertinus Mono|m|400
Cherish|h|400
Noto Sans Syriac|s|100 200 300 400 500 600 700 800 900
Noto Sans Pahawh Hmong|s|400
Noto Sans Tamil Supplement|s|400
Bahianita|d|400
Rubik Puddles|d|400
Wavefont|d|100 200 300 400 500 600 700 800 900 1000
Ruwudu|f|400 500 600 700
Tagesschrift|d|400
Rubik 80s Fade|d|400
Combo|d|400
M PLUS Code Latin|s|100 200 300 400 500 600 700
Butterfly Kids|h|400
Playpen Sans Hebrew|h|100 200 300 400 500 600 700 800
Sassy Frass|h|400
Playwrite PL|h|100 200 300 400
Playwrite DK Loopet|h|100 200 300 400
Noto Sans Shavian|s|400
Moulpali|s|400
Noto Sans Vithkuqi|s|400 500 600 700
Bungee Tint|d|400
Noto Serif Myanmar|f|100 200 300 400 500 600 700 800 900
Explora|h|400
Lilex|m|100 200 300 400 500 600 700
Iosevka Charon Mono|m|300 400 500 700
Playwrite CA|h|100 200 300 400
Kalnia Glaze|d|100 200 300 400 500 600 700
Flow Rounded|d|400
Rubik Beastly|d|400
Noto Serif Vithkuqi|f|400 500 600 700
Taprom|d|400
Matemasie|s|400
Linefont|d|100 200 300 400 500 600 700 800 900 1000
LXGW Marker Gothic|s|400
Noto Sans Yi|s|400
Noto Serif Dives Akuru|f|400
BBH Bogle|s|400
Agu Display|d|400
Zen Loop|d|400
Danfo|f|400
Asimovian|s|400
Noto Sans Carian|s|400
Langar|d|400
Noto Sans Siddham|s|400
Suravaram|f|400
WDXL Lubrifont TC|s|400
Karla Tamil Inclined|s|400 700
Estedad|s|100 200 300 400 500 600 700 800 900
Narnoor|s|400 500 600 700 800
Flow Block|d|400
Saira Stencil|d|100 200 300 400 500 600 700 800 900
Noto Serif Tangut|f|400
Annapurna SIL|f|400 700
Noto Sans Avestan|s|400
Playwrite HU|h|100 200 300 400
Noto Sans Runic|s|400
Noto Serif Dogra|f|400
Noto Serif Toto|f|400 500 600 700
Rubik Doodle Triangles|d|400
Playwrite NZ Basic|h|100 200 300 400
Noto Sans Hanunoo|s|400
Menbere|s|100 200 300 400 500 600 700
Geomini|s|200 300 400 500 600 700 800
Tai Heritage Pro|f|400 700
Playwrite DE SAS|h|100 200 300 400
Redacted Script|d|300 400 700
Phetsarath|s|400 700
UoqMunThenKhung|f|400
Estonia|h|400
Playwrite ZA|h|100 200 300 400
BBH Hegarty|s|400
Petemoss|h|400
Noto Sans Duployan|s|400 700
Noto Sans Multani|s|400
Labrada|f|100 200 300 400 500 600 700 800 900
Edu SA Hand|h|400 500 600 700
Ga Maamli|d|400
Noto Sans Marchen|s|400
Snowburst One|d|400
Tapestry|h|400
Coral Pixels|d|400
Geostar|d|400
Noto Sans Old Italic|s|400
Noto Sans Old Persian|s|400
Rubik Broken Fax|d|400
Rubik Maze|d|400
Noto Serif Balinese|f|400
Rubik Microbe|d|400
Noto Sans NKo|s|400
Savate|s|200 300 400 500 600 700 800 900
Noto Sans Mende Kikakui|s|400
Chokokutai|d|400
Noto Sans Bamum|s|400 500 600 700
Noto Sans Sunuwar|s|400
Datatype|m|100 200 300 400 500 600 700 800 900
Rock 3D|d|400
Moirai One|d|400
Lisu Bosa|f|200 300 400 500 600 700 800 900
Ruge Boogie|h|400
Noto Sans Takri|s|400
Playwrite IT Moderna|h|100 200 300 400
Namdhinggo|f|400 500 600 700 800
Playwrite NL|h|100 200 300 400
Winky Rough|s|300 400 500 600 700 800 900
Noto Sans Old Permic|s|400
Palette Mosaic|d|400
Playpen Sans Deva|h|100 200 300 400 500 600 700 800
Playwrite MX Guides|h|400
Noto Sans Nag Mundari|s|400 500 600 700
Playwrite AU TAS|h|100 200 300 400
Finlandica Text|s|100 200 300 400 500 600 700 800 900
Syne Tactile|d|400
Noto Traditional Nushu|s|300 400 500 600 700
Ingrid Darling|h|400
Playwrite AR|h|100 200 300 400
Mingzat|s|400
Hanalei|d|400
Tirra|s|400 500 600 700 800 900
M PLUS U|s|100 200 300 400 500 600 700 800 900
Miranda Sans|s|400 500 600 700
Noto Sans Lisu|s|400 500 600 700
Epunda Slab|f|300 400 500 600 700 800 900
Playwrite ES|h|100 200 300 400
Noto Sans Tifinagh|s|400
Noto Serif Gurmukhi|f|100 200 300 400 500 600 700 800 900
Edu AU VIC WA NT Pre|h|400 500 600 700
Libertinus Serif Display|d|400
Noto Sans Syriac Eastern|s|100 200 300 400 500 600 700 800 900
Jaini Purva|d|400
Playwrite MX|h|100 200 300 400
Hind Mysuru|s|300 400 500 600 700
Puppies Play|h|400
Noto Serif Makasar|f|400
Ponnala|d|400
Noto Sans Adlam Unjoined|s|400 500 600 700
Playwrite PT|h|100 200 300 400
Bitcount Ink|d|100 200 300 400 500 600 700 800 900
Playwrite BE VLG|h|100 200 300 400
Hibur Mono|m|400
Noto Sans Wancho|s|400
Rubik Marker Hatch|d|400
Noto Sans Egyptian Hieroglyphs|s|400
Edu QLD Beginner|h|400 500 600 700
Exile|d|400
Noto Serif Oriya|f|400 500 600 700
Grandiflora One|f|400
Shafarik|d|400
Noto Sans Nandinagari|s|400
Noto Sans Osage|s|400
Bitcount|d|100 200 300 400 500 600 700 800 900
Noto Sans Old Turkic|s|400
Playwrite AU VIC|h|100 200 300 400
Playpen Sans Thai|h|100 200 300 400 500 600 700 800
Blaka Hollow|d|400
Playwrite GB J|h|100 200 300 400
Playwrite HR Lijeva|h|100 200 300 400
Rubik Maps|d|400
Noto Sans Grantha|s|400
Moo Lah Lah|d|400
Edu VIC WA NT Hand Pre|h|400 500 600 700
Noto Sans Medefaidrin|s|400 500 600 700
Noto Sans Lydian|s|400
Noto Serif Khitan Small Script|f|400
Bytesized|s|400
Jaini|d|400
Noto Sans Old North Arabian|s|400
Noto Serif Todhri|f|400
Sirivennela|s|400
Playwrite DE LA|h|100 200 300 400
Noto Sans Vai|s|400
Noto Znamenny Musical Notation|s|400
Noto Sans NKo Unjoined|s|400 500 600 700
Noto Sans Indic Siyaq Numbers|s|400
Allkin|d|400
Noto Sans Nabataean|s|400
Playwrite FR Moderne|h|100 200 300 400
Bitcount Prop Double Ink|d|100 200 300 400 500 600 700 800 900
Noto Sans Mahajani|s|400
Playwrite NG Modern|h|100 200 300 400
Montenegrin Gothic One|f|400
Maname|f|400
Karla Tamil Upright|s|400 700
Bitcount Single Ink|d|100 200 300 400 500 600 700 800 900
Yuji Hentaigana Akari|h|400
Playwrite SK|h|100 200 300 400
Rubik Lines|d|400
Warnes|d|400
Rubik Storm|d|400
Noto Sans Tai Le|s|400
Playwrite CZ|h|100 200 300 400
Blaka Ink|d|400
Playwrite TZ|h|100 200 300 400
Kay Pho Du|f|400 500 600 700
Padyakke Expanded One|f|400
Playwrite BE WAL|h|100 200 300 400
Edu VIC WA NT Hand|h|400 500 600 700
Noto Sans Mandaic|s|400
Bitcount Prop Double|d|100 200 300 400 500 600 700 800 900
Edu AU VIC WA NT Arrows|h|400 500 600 700
Noto Sans Deseret|s|400
Noto Sans Cuneiform|s|400
Tuffy|s|400 700
Noto Serif NP Hmong|f|400 500 600 700
Sankofa Display|s|400
Noto Sans Inscriptional Parthian|s|400
Bitcount Grid Single Ink|d|100 200 300 400 500 600 700 800 900
Betania Patmos|h|400
Libertinus Keyboard|d|400
Noto Serif Ottoman Siyaq|f|400
Noto Sans Khojki|s|400
Jacquard 12 Charted|d|400
Noto Sans Sundanese|s|400 500 600 700
Playwrite NZ|h|100 200 300 400
Noto Sans Imperial Aramaic|s|400
Bpmf Zihi Kai Std|s|400
Noto Serif Hentaigana|f|200 300 400 500 600 700 800 900
Noto Sans Sogdian|s|400
Playwrite CO|h|100 200 300 400
Bitcount Prop Single Ink|d|100 200 300 400 500 600 700 800 900
Noto Sans New Tai Lue|s|400 500 600 700
Noto Sans Newa|s|400
Noto Sans Meroitic|s|400
BJCree|f|400 500 600 700
Strichpunkt Sans|s|400 500 600 700 800 900
Bitcount Grid Double Ink|d|100 200 300 400 500 600 700 800 900
Noto Sans Inscriptional Pahlavi|s|400
Noto Sans Palmyrene|s|400
Jersey 10 Charted|d|400
Noto Sans Tagbanwa|s|400
Noto Sans Cham|s|100 200 300 400 500 600 700 800 900
Yuyu|h|400
Edu NSW ACT Hand Pre|h|400 500 600 700
Noto Serif Grantha|f|400
Playwrite PE|h|100 200 300 400
Noto Sans Buginese|s|400
Noto Sans Zanabazar Square|s|400
Noto Sans Brahmi|s|400
Playwrite CO Guides|h|400
Noto Sans Miao|s|400
Jersey 15 Charted|d|400
Pochaevsk|d|400
Noto Sans Tai Tham|s|400 500 600 700
Playwrite US Trad Guides|h|400
Jacquard 24 Charted|d|400
Idiqlat|f|200 300 400
Playwrite ID|h|100 200 300 400
Noto Sans Hanifi Rohingya|s|400 500 600 700
Yuyu Short|h|400
Bpmf Iansui|h|400
Noto Sans Old South Arabian|s|400
Finlandica Headline|s|100 200 300 400 500 600 700 800 900
Noto Sans Sharada|s|400
Edu QLD Hand|h|400 500 600 700
Jersey 25 Charted|d|400
Matangi|s|300 400 500 600 700 800 900
Micro 5 Charted|d|400
Noto Sans Elymaic|s|400
Noto Serif Old Uyghur|f|400
Noto Sans Kawi|s|400 500 600 700
Yarndings 20 Charted|d|400
Playwrite CL|h|100 200 300 400
Noto Sans Ugaritic|s|400
Noto Sans Chakma|s|400
Noto Sans Rejang|s|400
Kanchenjunga|s|400 500 600 700
Noto Sans Bassa Vah|s|400 500 600 700
Jersey 20 Charted|d|400
Noto Sans Mro|s|400
Noto Sans Mayan Numerals|s|400
Noto Sans Tirhuta|s|400
Playwrite AU VIC Guides|h|400
Noto Sans Chorasmian|s|400
Noto Sans Kayah Li|s|400 500 600 700
Noto Sans Linear B|s|400
Playwrite ES Deco|h|100 200 300 400
Noto Sans Syriac Western|s|100 200 300 400 500 600 700 800 900
Playwrite NZ Guides|h|400
Noto Sans Hatran|s|400
Yarndings 20|d|400
Alien Block|d|400
Noto Sans Limbu|s|400
Noto Sans Pau Cin Hau|s|400
Noto Sans Cypriot|s|400
Noto Sans Masaram Gondi|s|400
Noto Sans Saurashtra|s|400
Noto Sans SignWriting|s|400
Noto Sans Kharoshthi|s|400
Noto Sans Gunjala Gondi|s|400 500 600 700
Noto Sans Lepcha|s|400
Noto Sans Manichaean|s|400
Noto Sans Old Sogdian|s|400
Noto Sans Phoenician|s|400
Betania Patmos In|h|400
Yuji Hentaigana Akebono|h|400
Playwrite NZ Basic Guides|h|400
Betania Patmos In GDL|h|400
Noto Sans Psalter Pahlavi|s|400
Jacquarda Bastarda 9 Charted|d|400
Playwrite GB J Guides|h|400
Playwrite TZ Guides|h|400
Noto Sans PhagsPa|s|400
Betania Patmos GDL|h|400
Noto Sans Lycian|s|400
Noto Sans Ogham|s|400
Noto Sans Soyombo|s|400
Yarndings 12|d|400
Playwrite PL Guides|h|400
Noto Sans Modi|s|400
Playwrite BR|h|100 200 300 400
Playwrite PT Guides|h|400
Playwrite CU Guides|h|400
Playwrite DE Grund Guides|h|400
Noto Sans Nushu|s|400
Ramsina|f|400
Playwrite DE VA|h|100 200 300 400
Playwrite PE Guides|h|400
Playwrite GB S Guides|h|400
Playwrite FR Trad|h|100 200 300 400
Playwrite IT Trad|h|100 200 300 400
Yarndings 12 Charted|d|400
Playwrite IN Guides|h|400
Playwrite BE WAL Guides|h|400
Playwrite IE Guides|h|400
Playwrite DE VA Guides|h|400
Playwrite AR Guides|h|400
Playwrite DK Uloopet Guides|h|400
Playwrite IT Moderna Guides|h|400
Playwrite FR Moderne Guides|h|400
Playwrite ES Deco Guides|h|400
Playwrite IT Trad Guides|h|400
Playwrite FR Trad Guides|h|400
Playwrite US Modern Guides|h|400
Playwrite ID Guides|h|400
Playwrite IS Guides|h|400
Playwrite AT Guides|h|400
Playwrite AU SA Guides|h|400
Playwrite HU Guides|h|400
Playwrite NG Modern Guides|h|400
Playwrite DK Loopet Guides|h|400
Playwrite AU NSW Guides|h|400
Playwrite CL Guides|h|400
Playwrite HR Lijeva Guides|h|400
Playwrite ZA Guides|h|400
Playwrite ES Guides|h|400
Playwrite NL Guides|h|400
Playwrite RO Guides|h|400
Playwrite AU TAS Guides|h|400
Playwrite SK Guides|h|400
Playwrite AU QLD Guides|h|400
Playwrite NO Guides|h|400
Playwrite BE VLG Guides|h|400
Playwrite CA Guides|h|400
Playwrite CZ Guides|h|400
Playwrite HR Guides|h|400`;
